### ISSUE TITLE
有关预训练权重文件的疑问

### ISSUE THREAD

**Issue by DYH200009** [phdymz/PointCLM#6]
请问您可以给出微调好的fun-tuned FCGF预训练权重文件吗，我目前只进行了modelnet40的复现工作，还没有进行Scan2CAD的复现

**Comment by phdymz** [comment]
我也发现我当时忘记上传这个权重了，代码和数据都比较久远了，近期没有整理的计划，后续如果扩展期刊的话会考虑找一下之前的一系列内容然后重新整理上来。
